name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [synchronize, opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install yarn and cache dependencies
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: Build project
        run: yarn build

      # Track bundle sizes and display in PR
      - uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}